### ISSUE TITLE
Set up repository

### ISSUE THREAD

**Issue by locks** [emberwatch/ember-language-server#1]
Use the node.js/TypeScript example server code.

cc @t-sauer

**Comment by chriskrycho** [comment]
ea30987e :tada:

**Comment by t-sauer** [comment]
It seems like you included both the server and the client from the example language server.  
Since the client is pretty much only the plugin for vscode to talk to the language server and the language server itself should be independant of any editors I think the client part should be removed. So basically I think we only need the server folder in here.

**Comment by chriskrycho** [comment]
@t-sauer happy to have it split it out; I initially left it in to make the feedback-and-testing loop short as we initially spin things up.
